# Generated by Django 4.0.5 on 2022-06-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address_1',
            new_name='address1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='address_2',
            new_name='address2',
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
