# Generated by Django 4.0.5 on 2022-06-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='file',
            field=models.ImageField(upload_to='products/%Y/%m/%d/'),
        ),
    ]
