# Generated by Django 4.0.5 on 2022-06-24 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.color'),
            preserve_default=False,
        ),
    ]
