# Generated by Django 4.0.5 on 2022-06-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslide',
            name='link',
            field=models.CharField(max_length=200),
        ),
    ]
