# Generated by Django 4.0.5 on 2022-06-27 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
