# Generated by Django 4.0.5 on 2022-06-29 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0006_alter_contact_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='heroslide',
            options={'ordering': ('order',), 'verbose_name': 'Hero слайд', 'verbose_name_plural': 'Hero слайды'},
        ),
    ]
