# Generated by Django 4.0.5 on 2022-06-26 07:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('transaction_id', models.CharField(blank=True, max_length=150)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_method', models.CharField(choices=[('post', 'Доставка почтой'), ('pickpoint', 'Постаматы PickPoint'), ('issuepoint', 'Пункт выдачи в Иркутске'), ('courier', 'Курьерская доставка по Иркутску')], default='post', max_length=20)),
                ('payment_method', models.CharField(choices=[('online', 'Онлайн'), ('cash', 'Наличный расчёт'), ('noncash', 'Безналичный расчёт'), ('installment', 'Рассрочка'), ('cod', 'Наложенный платеж')], default='online', max_length=20)),
                ('note', models.TextField(blank=True, max_length=300, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='coupons.coupon')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.variation')),
            ],
        ),
    ]
