# Generated by Django 4.0.5 on 2022-06-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_productimage_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='featured',
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='product/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='file',
            field=models.ImageField(upload_to='product_image/%Y/%m/%d/'),
        ),
    ]
