# Generated by Django 4.0.5 on 2022-06-07 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_remove_productimage_featured_product_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(default='/static/images/product-preview/placeholder.png', upload_to='product/%Y/%m/%d/'),
        ),
    ]
