# Generated by Django 4.0.5 on 2022-06-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_size_variation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='size',
            name='order',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
    ]
