# Generated by Django 4.0.5 on 2022-06-23 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_color_variation_color'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('slug', 'parent')},
        ),
    ]
